services:
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolidb
            MYSQL_USER: dolidbuser
            MYSQL_PASSWORD: dolidbpass
        container_name: mariadb

    web:
        image: dolibarr/dolibarr:latest
        environment:
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
            DOLI_DB_HOST: mariadb
            DOLI_DB_NAME: dolidb
            DOLI_DB_USER: dolidbuser
            DOLI_DB_PASSWORD: dolidbpass
            DOLI_URL_ROOT: "http://0.0.0.0"
            DOLI_ADMIN_LOGIN: "admin"
            DOLI_ADMIN_PASSWORD: "admin"
            DOLI_CRON: 0
            DOLI_INIT_DEMO: 0
            DOLI_COMPANY_NAME: MyBigCompany

        ports:
            - "80:80"
        links:
            - mariadb
